Phase 1 : Genrate Raw data(bad data)

Import Required Libraries

In [4]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

print("Libraries Imported Successfully")

Libraries Imported Successfully

Set Random Seed

In [5]:
random.seed(10)
np.random.seed(10)

print("Random Seed Set")

Random Seed Set

 Create Lists:

 Customer Names

In [6]:
customer_names = [
    "Aarav","Vivaan","Aditya","Vihaan","Arjun",
    "Sai","Krishna","Ananya","Diya","Aisha",
    "Riya","Sneha","Priya","Rahul","Aman",
    "Harsh","Karan","Rohan","Neha","Pooja"
]

categories = [
    "Electronics",
    "Clothing",
    "Home",
    "Books"
]

products = [
    "Laptop",
    "Mobile",
    "Headphones",
    "Shoes",
    "T Shirt",
    "Mixer",
    "Chair",
    "Table",
    "Novel",
    "Notebook",
    "Keyboard",
    "Mouse",
    "Watch",
    "Bag",
    "Bottle"
]

regions = [
    "North",
    "South",
    "East",
    "West"
]

status_list = [
    "PLACED",
    "SHIPPED",
    "DELIVERED",
    "CANCELLED",
    "RETURNED"
]

print("Lists Created Successfully")

Lists Created Successfully

Generate Customers Dataset

In [7]:
customer_data = []

customer_types = ["REGULAR", "PREMIUM", "VIP"]

for i in range(1, 501):

    customer_id = "C" + str(i).zfill(4)

    customer_name = random.choice(customer_names)

    email = customer_name.lower() + str(i) + "@gmail.com"

    registration_date = datetime(2023,1,1) + timedelta(days=random.randint(0,700))

    customer_type = random.choice(customer_types)

    customer_data.append([
        customer_id,
        customer_name,
        email,
        registration_date.strftime("%Y-%m-%d"),
        customer_type
    ])

customers_df = pd.DataFrame(
    customer_data,
    columns=[
        "customer_id",
        "customer_name",
        "email",
        "registration_date",
        "customer_type"
    ]
)

customers_df.head()

,customer_id,customer_name,email,registration_date,customer_type
0,C0001,Neha,neha1@gmail.com,2023-02-03,PREMIUM
1,C0002,Harsh,harsh2@gmail.com,2024-08-14,REGULAR
2,C0003,Krishna,krishna3@gmail.com,2024-04-18,PREMIUM
3,C0004,Diya,diya4@gmail.com,2024-10-31,REGULAR
4,C0005,Vivaan,vivaan5@gmail.com,2024-06-17,PREMIUM

Introduce Invalid Emails

In [8]:
invalid_rows = random.sample(range(500), 10)

for i in invalid_rows:

    customers_df.loc[i, "email"] = "invalidemail.com"

Introduce Missing Emails

In [9]:
missing_rows = random.sample(range(500), 10)

for i in missing_rows:

    customers_df.loc[i, "email"] = np.nan

customers_df.head(15)

,customer_id,customer_name,email,registration_date,customer_type
0,C0001,Neha,neha1@gmail.com,2023-02-03,PREMIUM
1,C0002,Harsh,harsh2@gmail.com,2024-08-14,REGULAR
2,C0003,Krishna,krishna3@gmail.com,2024-04-18,PREMIUM
3,C0004,Diya,diya4@gmail.com,2024-10-31,REGULAR
4,C0005,Vivaan,vivaan5@gmail.com,2024-06-17,PREMIUM
5,C0006,Riya,riya6@gmail.com,2023-03-19,REGULAR
6,C0007,Sneha,sneha7@gmail.com,2023-02-15,PREMIUM
7,C0008,Arjun,arjun8@gmail.com,2024-09-09,PREMIUM
8,C0009,Priya,priya9@gmail.com,2024-03-07,PREMIUM
9,C0010,Diya,diya10@gmail.com,2024-04-12,REGULAR
10,C0011,Aisha,aisha11@gmail.com,2024-11-08,PREMIUM
11,C0012,Arjun,arjun12@gmail.com,2024-04-12,REGULAR
12,C0013,Aman,aman13@gmail.com,2024-09-20,PREMIUM
13,C0014,Vivaan,vivaan14@gmail.com,2024-08-19,REGULAR
14,C0015,Ananya,ananya15@gmail.com,2023-05-18,REGULAR

Save Customers Dataset

In [10]:
customers_df.to_csv("customers.csv", index=False)

print("customers.csv saved successfully.")

customers.csv saved successfully.

In [11]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        500 non-null    object
 1   customer_name      500 non-null    object
 2   email              490 non-null    object
 3   registration_date  500 non-null    object
 4   customer_type      500 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

Generate Products Dataset

In [12]:
subcategories = {
    "Electronics": ["Laptop", "Mobile", "Accessories"],
    "Clothing": ["Men", "Women", "Kids"],
    "Home": ["Furniture", "Kitchen", "Decor"],
    "Books": ["Education", "Novel", "Comics"]
}

product_data = []

for i in range(1, 501):

    product_id = "P" + str(i).zfill(4)

    category = random.choice(categories)

    subcategory = random.choice(subcategories[category])

    product_name = random.choice(products)

    cost_price = random.randint(100, 5000)

    product_data.append([
        product_id,
        product_name,
        category,
        subcategory,
        cost_price
    ])

products_df = pd.DataFrame(
    product_data,
    columns=[
        "product_id",
        "product_name",
        "category",
        "subcategory",
        "cost_price"
    ]
)

products_df.head()

  product_id product_name  category subcategory  cost_price
0      P0001        Table  Clothing        Kids        3927
1      P0002        Table      Home       Decor         104
2      P0003      T Shirt      Home   Furniture        4410
3      P0004     Notebook      Home   Furniture        3439
4      P0005        Chair     Books       Novel         733

Introduce Mixed Case Product Names

In [13]:
mixed_case_rows = random.sample(range(500), 20)

for i in mixed_case_rows:

    products_df.loc[i, "product_name"] = products_df.loc[i, "product_name"].upper()

Introduce Extra Spaces

In [14]:
space_rows = random.sample(range(500), 20)

for i in space_rows:

    products_df.loc[i, "product_name"] = "  " + products_df.loc[i, "product_name"] + "   "

products_df.head(20)

   product_id product_name     category  subcategory  cost_price
0       P0001        Table     Clothing         Kids        3927
1       P0002        Table         Home        Decor         104
2       P0003      T Shirt         Home    Furniture        4410
3       P0004     Notebook         Home    Furniture        3439
4       P0005        Chair        Books        Novel         733
5       P0006          Bag         Home    Furniture        2918
6       P0007       MOBILE     Clothing          Men        3179
7       P0008        Shoes         Home    Furniture         461
8       P0009        Watch         Home      Kitchen        3643
9       P0010       Mobile        Books       Comics        2252
10      P0011        Chair         Home        Decor        2139
11      P0012      T Shirt  Electronics  Accessories        1958
12      P0013       Laptop         Home    Furniture        1785
13      P0014       Laptop     Clothing          Men        1090
14      P0015        Table         Home      Kitchen        1016
15      P0016     Notebook         Home    Furniture        4624
16      P0017        Mixer        Books       Comics         948
17      P0018        CHAIR        Books        Novel        3550
18      P0019        MIXER  Electronics  Accessories        2828
19      P0020     Notebook  Electronics  Accessories         956

Save Products Dataset

In [15]:
products_df.to_csv("products.csv", index=False)

print("products.csv saved successfully.")

products_df.info()

products.csv saved successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    object
 1   product_name  500 non-null    object
 2   category      500 non-null    object
 3   subcategory   500 non-null    object
 4   cost_price    500 non-null    int64
dtypes: int64(1), object(4)
memory usage: 19.7+ KB

Generate Orders Dataset

In [16]:
order_data = []

for i in range(1, 501):

    order_id = "O" + str(i).zfill(4)

    customer_id = "C" + str(random.randint(1, 500)).zfill(4)

    order_date = datetime(2024, 1, 1) + timedelta(days=random.randint(0, 365))

    status = random.choice(status_list)

    region_code = random.choice(regions)

    order_data.append([
        order_id,
        customer_id,
        order_date.strftime("%Y-%m-%d %H:%M:%S"),
        status,
        region_code
    ])

orders_df = pd.DataFrame(
    order_data,
    columns=[
        "order_id",
        "customer_id",
        "order_date",
        "status",
        "region_code"
    ]
)

orders_df.head()

  order_id customer_id           order_date     status region_code
0    O0001       C0305  2024-07-12 00:00:00  DELIVERED       North
1    O0002       C0383  2024-09-15 00:00:00    SHIPPED        East
2    O0003       C0267  2024-03-03 00:00:00   RETURNED       North
3    O0004       C0495  2024-09-11 00:00:00    SHIPPED        West
4    O0005       C0108  2024-06-07 00:00:00    SHIPPED       South

Introduce NULL Customer IDs (5%)

In [17]:
null_rows = random.sample(range(500), 25)

for i in null_rows:

    orders_df.loc[i, "customer_id"] = np.nan

Introduce Wrong Date Format

In [18]:
wrong_date_rows = random.sample(range(500), 15)

for i in wrong_date_rows:

    date = pd.to_datetime(orders_df.loc[i, "order_date"])

    orders_df.loc[i, "order_date"] = date.strftime("%d-%m-%Y")

orders_df.head(20)

   order_id customer_id           order_date     status region_code
0     O0001       C0305  2024-07-12 00:00:00  DELIVERED       North
1     O0002       C0383  2024-09-15 00:00:00    SHIPPED        East
2     O0003       C0267  2024-03-03 00:00:00   RETURNED       North
3     O0004       C0495  2024-09-11 00:00:00    SHIPPED        West
4     O0005       C0108  2024-06-07 00:00:00    SHIPPED       South
5     O0006       C0288  2024-04-18 00:00:00    SHIPPED       South
6     O0007       C0008  2024-12-16 00:00:00  DELIVERED        East
7     O0008       C0108  2024-05-25 00:00:00  CANCELLED        West
8     O0009       C0258  2024-05-19 00:00:00    SHIPPED        East
9     O0010       C0030  2024-03-04 00:00:00    SHIPPED       South
10    O0011       C0400  2024-08-30 00:00:00  DELIVERED       South
11    O0012       C0156  2024-03-09 00:00:00    SHIPPED        West
12    O0013       C0078  2024-10-18 00:00:00  CANCELLED        East
13    O0014         NaN  2024-02-15 00:00:00  CANCELLED        West
14    O0015       C0490  2024-03-27 00:00:00   RETURNED       North
15    O0016         NaN  2024-05-19 00:00:00    SHIPPED        East
16    O0017       C0303           06-04-2024   RETURNED       North
17    O0018       C0280  2024-10-07 00:00:00     PLACED       South
18    O0019         NaN  2024-01-16 00:00:00  DELIVERED        West
19    O0020       C0399  2024-07-10 00:00:00     PLACED       North

Save Orders Dataset

In [20]:
orders_df.to_csv("orders.csv", index=False)

print("orders.csv saved successfully.")

orders_df.info()

orders.csv saved successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     500 non-null    object
 1   customer_id  475 non-null    object
 2   order_date   500 non-null    object
 3   status       500 non-null    object
 4   region_code  500 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

Generate Order Items Dataset

In [21]:
item_data = []

for i in range(1, 501):

    item_id = "I" + str(i).zfill(4)

    order_id = "O" + str(random.randint(1, 500)).zfill(4)

    product_id = "P" + str(random.randint(1, 500)).zfill(4)

    quantity = random.randint(1, 5)

    unit_price = random.randint(200, 5000)

    discount_percent = random.randint(0, 50)

    item_data.append([
        item_id,
        order_id,
        product_id,
        quantity,
        unit_price,
        discount_percent
    ])

order_items_df = pd.DataFrame(
    item_data,
    columns=[
        "item_id",
        "order_id",
        "product_id",
        "quantity",
        "unit_price",
        "discount_percent"
    ]
)

order_items_df.head()

  item_id order_id product_id  quantity  unit_price  discount_percent
0   I0001    O0224      P0155         2        2049                13
1   I0002    O0300      P0383         1        1339                28
2   I0003    O0041      P0087         4        1022                27
3   I0004    O0089      P0062         4        4856                35
4   I0005    O0377      P0031         5        2857                15

Negative Quantity (3%)

In [22]:
negative_rows = random.sample(range(500), 15)

for i in negative_rows:

    order_items_df.loc[i, "quantity"] = -random.randint(1, 5)

Invalid Order IDs

In [23]:
invalid_order_rows = random.sample(range(500), 10)

for i in invalid_order_rows:

    order_items_df.loc[i, "order_id"] = "O9999"

Discount Greater Than 100

In [24]:
discount_rows = random.sample(range(500), 5)

for i in discount_rows:

    order_items_df.loc[i, "discount_percent"] = 120

order_items_df.head(20)

   item_id order_id product_id  quantity  unit_price  discount_percent
0    I0001    O0224      P0155         2        2049                13
1    I0002    O0300      P0383         1        1339                28
2    I0003    O0041      P0087         4        1022                27
3    I0004    O0089      P0062         4        4856                35
4    I0005    O0377      P0031         5        2857                15
5    I0006    O0320      P0212         1        1320                17
6    I0007    O0222      P0025         4        1924                16
7    I0008    O0465      P0379         5        1266                 7
8    I0009    O0199      P0500         3        3624                39
9    I0010    O0124      P0069         3        2310                49
10   I0011    O0437      P0150         3        1454                 7
11   I0012    O0371      P0491         1        2085                24
12   I0013    O0231      P0139         3        2191                10
13   I0014    O0487      P0310         5        1445                22
14   I0015    O0064      P0376         5        4481                 2
15   I0016    O0343      P0133         3        2707                26
16   I0017    O0299      P0409         2        2198                20
17   I0018    O0061      P0279         3        3098                 5
18   I0019    O9999      P0455         1        4993                28
19   I0020    O9999      P0422         5        1682                38

Save Order Items Dataset

In [25]:
order_items_df.to_csv("order_items.csv", index=False)

print("order_items.csv saved successfully.")

order_items_df.info()

order_items.csv saved successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id           500 non-null    object
 1   order_id          500 non-null    object
 2   product_id        500 non-null    object
 3   quantity          500 non-null    int64
 4   unit_price        500 non-null    int64
 5   discount_percent  500 non-null    int64
dtypes: int64(3), object(3)
memory usage: 23.6+ KB

In [26]:
print("Customers Dataset")
display(customers_df.head())

print("\nProducts Dataset")
display(products_df.head())

print("\nOrders Dataset")
display(orders_df.head())

print("\nOrder Items Dataset")
display(order_items_df.head())

Customers Dataset

,customer_id,customer_name,email,registration_date,customer_type
0,C0001,Neha,neha1@gmail.com,2023-02-03,PREMIUM
1,C0002,Harsh,harsh2@gmail.com,2024-08-14,REGULAR
2,C0003,Krishna,krishna3@gmail.com,2024-04-18,PREMIUM
3,C0004,Diya,diya4@gmail.com,2024-10-31,REGULAR
4,C0005,Vivaan,vivaan5@gmail.com,2024-06-17,PREMIUM

Products Dataset

  product_id product_name  category subcategory  cost_price
0      P0001        Table  Clothing        Kids        3927
1      P0002        Table      Home       Decor         104
2      P0003      T Shirt      Home   Furniture        4410
3      P0004     Notebook      Home   Furniture        3439
4      P0005        Chair     Books       Novel         733

Orders Dataset

  order_id customer_id           order_date     status region_code
0    O0001       C0305  2024-07-12 00:00:00  DELIVERED       North
1    O0002       C0383  2024-09-15 00:00:00    SHIPPED        East
2    O0003       C0267  2024-03-03 00:00:00   RETURNED       North
3    O0004       C0495  2024-09-11 00:00:00    SHIPPED        West
4    O0005       C0108  2024-06-07 00:00:00    SHIPPED       South

Order Items Dataset

  item_id order_id product_id  quantity  unit_price  discount_percent
0   I0001    O0224      P0155         2        2049                13
1   I0002    O0300      P0383         1        1339                28
2   I0003    O0041      P0087         4        1022                27
3   I0004    O0089      P0062         4        4856                35
4   I0005    O0377      P0031         5        2857                15

In [29]:
print("Shape of Customers Dataset :", customers_df.shape)
print("Shape of Products Dataset :", products_df.shape)
print("Shape of Orders Dataset :", orders_df.shape)
print("Shape of Order Items Dataset :", order_items_df.shape)

Shape of Customers Dataset : (500, 5)
Shape of Products Dataset : (500, 5)
Shape of Orders Dataset : (500, 5)
Shape of Order Items Dataset : (500, 6)

Save All Raw Datasets

In [34]:
import os

os.makedirs("raw_data", exist_ok=True)
os.makedirs("cleaned_data", exist_ok=True)
os.makedirs("reports", exist_ok=True)

In [35]:
customers_df.to_csv("raw_data/customers.csv", index=False)

products_df.to_csv("raw_data/products.csv", index=False)

orders_df.to_csv("raw_data/orders.csv", index=False)

order_items_df.to_csv("raw_data/order_items.csv", index=False)

In [36]:
import os

print("Files inside raw_data folder:\n")

for file in os.listdir("raw_data"):
    print(file)

Files inside raw_data folder:

customers.csv
products.csv
order_items.csv
orders.csv

In [37]:
raw_customers = pd.read_csv("raw_data/customers.csv")

raw_customers.head()

,customer_id,customer_name,email,registration_date,customer_type
0,C0001,Neha,neha1@gmail.com,2023-02-03,PREMIUM
1,C0002,Harsh,harsh2@gmail.com,2024-08-14,REGULAR
2,C0003,Krishna,krishna3@gmail.com,2024-04-18,PREMIUM
3,C0004,Diya,diya4@gmail.com,2024-10-31,REGULAR
4,C0005,Vivaan,vivaan5@gmail.com,2024-06-17,PREMIUM

In [38]:
customers_df.to_excel("customers.xlsx", index=False)

products_df.to_excel("products.xlsx", index=False)

orders_df.to_excel("orders.xlsx", index=False)

order_items_df.to_excel("order_items.xlsx", index=False)

In [41]:
from google.colab import files

files.download("customers.xlsx")
files.download("products.xlsx")
files.download("orders.xlsx")
files.download("order_items.xlsx")

Phase 2 : Cleaning data

In [42]:
customers = pd.read_csv("customers.csv")

products = pd.read_csv("products.csv")

orders = pd.read_csv("orders.csv")

order_items = pd.read_csv("order_items.csv")

Check Missing Values

In [44]:
print("Customers Missing Values")

print(customers.isnull().sum())

print("--------------------------------")

print("Products Missing Values")

print(products.isnull().sum())

print("--------------------------------")

print("Orders Missing Values")

print(orders.isnull().sum())

print("--------------------------------")

print("Order Items Missing Values")

print(order_items.isnull().sum())

Customers Missing Values
customer_id           0
customer_name         0
email                10
registration_date     0
customer_type         0
dtype: int64
--------------------------------
Products Missing Values
product_id      0
product_name    0
category        0
subcategory     0
cost_price      0
dtype: int64
--------------------------------
Orders Missing Values
order_id        0
customer_id    25
order_date      0
status          0
region_code     0
dtype: int64
--------------------------------
Order Items Missing Values
item_id             0
order_id            0
product_id          0
quantity            0
unit_price          0
discount_percent    0
dtype: int64

Check Duplicate Records

In [45]:
print("Duplicate Customers :", customers.duplicated().sum())

print("Duplicate Products :", products.duplicated().sum())

print("Duplicate Orders :", orders.duplicated().sum())

print("Duplicate Order Items :", order_items.duplicated().sum())

Duplicate Customers : 0
Duplicate Products : 0
Duplicate Orders : 0
Duplicate Order Items : 0

Clean Customers Dataset

In [46]:
def clean_customers(df):

    # Remove extra spaces
    df["customer_name"] = df["customer_name"].str.strip()

    # Convert email to lowercase
    df["email"] = df["email"].str.lower()

    # Fill missing email
    df["email"] = df["email"].fillna("unknown@gmail.com")

    return df

customers = clean_customers(customers)

In [47]:
customers.head(10)

,customer_id,customer_name,email,registration_date,customer_type
0,C0001,Neha,neha1@gmail.com,2023-02-03,PREMIUM
1,C0002,Harsh,harsh2@gmail.com,2024-08-14,REGULAR
2,C0003,Krishna,krishna3@gmail.com,2024-04-18,PREMIUM
3,C0004,Diya,diya4@gmail.com,2024-10-31,REGULAR
4,C0005,Vivaan,vivaan5@gmail.com,2024-06-17,PREMIUM
5,C0006,Riya,riya6@gmail.com,2023-03-19,REGULAR
6,C0007,Sneha,sneha7@gmail.com,2023-02-15,PREMIUM
7,C0008,Arjun,arjun8@gmail.com,2024-09-09,PREMIUM
8,C0009,Priya,priya9@gmail.com,2024-03-07,PREMIUM
9,C0010,Diya,diya10@gmail.com,2024-04-12,REGULAR

Validate Emails

In [48]:
def validate_emails(df):

    invalid_email = df[~df["email"].str.contains("@", na=False)]

    return invalid_email

invalid_email_df = validate_emails(customers)

print("Number of Invalid Emails :", len(invalid_email_df))

invalid_email_df

Number of Invalid Emails : 10

,customer_id,customer_name,email,registration_date,customer_type
56,C0057,Riya,invalidemail.com,2024-10-27,VIP
190,C0191,Harsh,invalidemail.com,2023-06-08,REGULAR
295,C0296,Pooja,invalidemail.com,2024-06-13,VIP
327,C0328,Diya,invalidemail.com,2023-06-13,PREMIUM
336,C0337,Aditya,invalidemail.com,2024-10-24,REGULAR
363,C0364,Aisha,invalidemail.com,2024-06-05,REGULAR
446,C0447,Ananya,invalidemail.com,2023-09-04,PREMIUM
464,C0465,Aisha,invalidemail.com,2023-02-20,REGULAR
467,C0468,Rahul,invalidemail.com,2023-01-21,VIP
487,C0488,Pooja,invalidemail.com,2024-01-16,VIP

Fix Invalid Emails

In [50]:
customers["email"] = customers["email"].apply(
    lambda x: "unknown@gmail.com" if "@" not in str(x) else x
)

customers["email"].str.contains("@").value_counts()

email
True    500
Name: count, dtype: int64

In [51]:
customers.isnull().sum()

customer_id          0
customer_name        0
email                0
registration_date    0
customer_type        0
dtype: int64

In [52]:
customers.to_excel("customers_clean.xlsx", index=False)

In [53]:
customers.head()

,customer_id,customer_name,email,registration_date,customer_type
0,C0001,Neha,neha1@gmail.com,2023-02-03,PREMIUM
1,C0002,Harsh,harsh2@gmail.com,2024-08-14,REGULAR
2,C0003,Krishna,krishna3@gmail.com,2024-04-18,PREMIUM
3,C0004,Diya,diya4@gmail.com,2024-10-31,REGULAR
4,C0005,Vivaan,vivaan5@gmail.com,2024-06-17,PREMIUM

Clean Products Dataset

In [54]:
def clean_products(df):

    df["product_name"] = df["product_name"].str.strip()

    df["product_name"] = df["product_name"].str.title()

    return df

products = clean_products(products)

In [55]:
products.head(6)

  product_id product_name  category subcategory  cost_price
0      P0001        Table  Clothing        Kids        3927
1      P0002        Table      Home       Decor         104
2      P0003      T Shirt      Home   Furniture        4410
3      P0004     Notebook      Home   Furniture        3439
4      P0005        Chair     Books       Novel         733
5      P0006          Bag      Home   Furniture        2918

In [56]:
products.isnull().sum()

product_id      0
product_name    0
category        0
subcategory     0
cost_price      0
dtype: int64

Check Duplicate Products

In [57]:
print("Duplicate Rows :", products.duplicated().sum())

Duplicate Rows : 0

In [58]:
products.head(15)

   product_id product_name     category  subcategory  cost_price
0       P0001        Table     Clothing         Kids        3927
1       P0002        Table         Home        Decor         104
2       P0003      T Shirt         Home    Furniture        4410
3       P0004     Notebook         Home    Furniture        3439
4       P0005        Chair        Books        Novel         733
5       P0006          Bag         Home    Furniture        2918
6       P0007       Mobile     Clothing          Men        3179
7       P0008        Shoes         Home    Furniture         461
8       P0009        Watch         Home      Kitchen        3643
9       P0010       Mobile        Books       Comics        2252
10      P0011        Chair         Home        Decor        2139
11      P0012      T Shirt  Electronics  Accessories        1958
12      P0013       Laptop         Home    Furniture        1785
13      P0014       Laptop     Clothing          Men        1090
14      P0015        Table         Home      Kitchen        1016

In [59]:
products.to_excel("products_clean.xlsx", index=False)

In [60]:
print(products.shape)

products.info()

(500, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    object
 1   product_name  500 non-null    object
 2   category      500 non-null    object
 3   subcategory   500 non-null    object
 4   cost_price    500 non-null    int64
dtypes: int64(1), object(4)
memory usage: 19.7+ KB

Clean Orders Dataset

In [68]:
orders.head(78)

   order_id customer_id           order_date     status region_code
0     O0001       C0305  2024-07-12 00:00:00  DELIVERED       North
1     O0002       C0383  2024-09-15 00:00:00    SHIPPED        East
2     O0003       C0267  2024-03-03 00:00:00   RETURNED       North
3     O0004       C0495  2024-09-11 00:00:00    SHIPPED        West
4     O0005       C0108  2024-06-07 00:00:00    SHIPPED       South
..      ...         ...                  ...        ...         ...
73    O0074       C0327  2024-07-26 00:00:00     PLACED        West
74    O0075       C0491  2024-06-11 00:00:00     PLACED        East
75    O0076       C0163  2024-02-13 00:00:00    SHIPPED       South
76    O0077         NaN  2024-12-17 00:00:00  CANCELLED        West
77    O0078       C0047  2024-11-21 00:00:00  DELIVERED        East

[78 rows x 5 columns]

In [61]:
print(orders.isnull().sum())

order_id        0
customer_id    25
order_date      0
status          0
region_code     0
dtype: int64

In [62]:
display(orders["order_date"].head(10))

0    2024-07-12 00:00:00
1    2024-09-15 00:00:00
2    2024-03-03 00:00:00
3    2024-09-11 00:00:00
4    2024-06-07 00:00:00
5    2024-04-18 00:00:00
6    2024-12-16 00:00:00
7    2024-05-25 00:00:00
8    2024-05-19 00:00:00
9    2024-03-04 00:00:00
Name: order_date, dtype: object

In [69]:
def clean_orders(df):

    df["customer_id"] = df["customer_id"].fillna("Unknown")
    df["order_date"] = pd.to_datetime(
        df["order_date"],
        errors="coerce",
        format="mixed"
    )

    return df

orders = clean_orders(orders)

In [70]:
orders.head(10)

  order_id customer_id order_date     status region_code
0    O0001       C0305 2024-07-12  DELIVERED       North
1    O0002       C0383 2024-09-15    SHIPPED        East
2    O0003       C0267 2024-03-03   RETURNED       North
3    O0004       C0495 2024-09-11    SHIPPED        West
4    O0005       C0108 2024-06-07    SHIPPED       South
5    O0006       C0288 2024-04-18    SHIPPED       South
6    O0007       C0008 2024-12-16  DELIVERED        East
7    O0008       C0108 2024-05-25  CANCELLED        West
8    O0009       C0258 2024-05-19    SHIPPED        East
9    O0010       C0030 2024-03-04    SHIPPED       South

In [71]:
print(orders.isnull().sum())

order_id       0
customer_id    0
order_date     0
status         0
region_code    0
dtype: int64

Convert Date Format

In [72]:
orders["order_date"] = orders["order_date"].dt.strftime("%Y-%m-%d %H:%M:%S")

In [73]:
orders.head()

  order_id customer_id           order_date     status region_code
0    O0001       C0305  2024-07-12 00:00:00  DELIVERED       North
1    O0002       C0383  2024-09-15 00:00:00    SHIPPED        East
2    O0003       C0267  2024-03-03 00:00:00   RETURNED       North
3    O0004       C0495  2024-09-11 00:00:00    SHIPPED        West
4    O0005       C0108  2024-06-07 00:00:00    SHIPPED       South

In [76]:
orders.to_excel("orders_clean.xlsx", index=False)
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     500 non-null    object
 1   customer_id  500 non-null    object
 2   order_date   500 non-null    object
 3   status       500 non-null    object
 4   region_code  500 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

Clean Order Items

In [77]:
print(order_items.isnull().sum())

item_id             0
order_id            0
product_id          0
quantity            0
unit_price          0
discount_percent    0
dtype: int64

In [80]:
(order_items["quantity"] < 0).sum()

np.int64(15)

In [81]:
(order_items["discount_percent"] > 100).sum()

np.int64(5)

In [82]:
def clean_order_items(df):

    df["quantity"] = df["quantity"].abs()

    df.loc[df["discount_percent"] > 100, "discount_percent"] = 100

    return df

order_items = clean_order_items(order_items)

In [83]:
order_items.head(10)

  item_id order_id product_id  quantity  unit_price  discount_percent
0   I0001    O0224      P0155         2        2049                13
1   I0002    O0300      P0383         1        1339                28
2   I0003    O0041      P0087         4        1022                27
3   I0004    O0089      P0062         4        4856                35
4   I0005    O0377      P0031         5        2857                15
5   I0006    O0320      P0212         1        1320                17
6   I0007    O0222      P0025         4        1924                16
7   I0008    O0465      P0379         5        1266                 7
8   I0009    O0199      P0500         3        3624                39
9   I0010    O0124      P0069         3        2310                49

In [84]:
order_items.to_excel("order_items_clean.xlsx", index=False)

In [85]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id           500 non-null    object
 1   order_id          500 non-null    object
 2   product_id        500 non-null    object
 3   quantity          500 non-null    int64
 4   unit_price        500 non-null    int64
 5   discount_percent  500 non-null    int64
dtypes: int64(3), object(3)
memory usage: 23.6+ KB

Downloading the clean files

In [95]:
from google.colab import files

files.download("customers_clean.xlsx")
files.download("products_clean.xlsx")
files.download("orders_clean.xlsx")

Check Referential Integrity

In [87]:
def check_referential_integrity(order_items_df, orders_df):

    invalid_orders = order_items_df[
        ~order_items_df["order_id"].isin(orders_df["order_id"])
    ]

    return invalid_orders

invalid_orders = check_referential_integrity(order_items, orders)

print("Number of Invalid Order IDs :", len(invalid_orders))

Number of Invalid Order IDs : 10

In [88]:
invalid_orders

    item_id order_id product_id  quantity  unit_price  discount_percent
18    I0019    O9999      P0455         1        4993                28
19    I0020    O9999      P0422         5        1682                38
71    I0072    O9999      P0269         2        2768                26
109   I0110    O9999      P0251         2         206                 4
287   I0288    O9999      P0026         3        4884                16
304   I0305    O9999      P0447         1         803                38
334   I0335    O9999      P0134         5        2032                29
435   I0436    O9999      P0057         2        3254                21
447   I0448    O9999      P0168         3        4774                 8
448   I0449    O9999      P0065         1        1195                 0

Remove Invalid Order IDs

In [89]:
order_items = order_items[
    order_items["order_id"].isin(orders["order_id"])
]

In [90]:
print("Updated Shape")

order_items.shape

Updated Shape

(490, 6)

In [91]:
invalid_orders = check_referential_integrity(order_items, orders)

In [92]:
print("Remaining Invalid Records :", len(invalid_orders))

Remaining Invalid Records : 0

In [93]:
order_items.to_excel("order_items_clean.xlsx", index=False)

In [94]:
from google.colab import files
files.download("order_items_clean.xlsx")

Saving and downloading csv's as well as we have to import it in database.

In [96]:
customers.to_csv("customers_clean.csv", index=False)

products.to_csv("products_clean.csv", index=False)

orders.to_csv("orders_clean.csv", index=False)

order_items.to_csv("order_items_clean.csv", index=False)

In [97]:
from google.colab import files

files.download("customers_clean.csv")
files.download("products_clean.csv")
files.download("orders_clean.csv")
files.download("order_items_clean.csv")

Phase 3 : SQL Analysis

In [ ]:
It was done in MySql Workbench 8.0 .

Phase 4: Python + SQL Integration

Import Library

In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (9.7.0)

[notice] A new release of pip available: 22.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Import Libraries

In [2]:
import mysql.connector
from datetime import datetime

Connect Database

In [3]:
try:
    connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="WJ28@KRHPS",
        database="ecommerce_order_analytics"
    )

    cursor = connection.cursor()

    print("Database Connected Successfully!")

except mysql.connector.Error as err:

    print("Connection Failed")

    print(err)

Database Connected Successfully!

User input

In [4]:
report_type = "Monthly"

start_date = "2024-01-01"

end_date = "2024-12-31"

print("Report Type :", report_type)
print("Start Date :", start_date)
print("End Date :", end_date)

Report Type : Monthly
Start Date : 2024-01-01
End Date : 2024-12-31

In [5]:
report_type = input("Enter Report Type (Daily/Weekly/Monthly): ")

start_date = input("Enter Start Date (YYYY-MM-DD): ")

end_date = input("Enter End Date (YYYY-MM-DD): ")

print("\nUser Inputs Received Successfully!\n")

print("Report Type :", report_type)
print("Start Date  :", start_date)
print("End Date    :", end_date)

User Inputs Received Successfully!

Report Type : Daily
Start Date  : 2024-01-01
End Date    : 2024-12-31

Generate Summary Report

In [7]:
summary_query = """
SELECT
COUNT(DISTINCT o.order_id) AS total_orders,
ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent / 100)),2) AS total_revenue,
COUNT(DISTINCT o.customer_id) AS unique_customers
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
WHERE DATE(o.order_date)
BETWEEN %s AND %s;
"""

cursor.execute(summary_query, (start_date, end_date))

summary = cursor.fetchone()


print("Report Type       :", report_type)
print("Date Range        :", start_date, "to", end_date)


print("Total Orders      :", summary[0])
print("Total Revenue     : ₹", summary[1])
print("Unique Customers  :", summary[2])

Report Type       : Daily
Date Range        : 2024-01-01 to 2024-12-31
Total Orders      : 296
Total Revenue     : ₹ 2717167.91
Unique Customers  : 225

Top 3 Products

In [8]:
top_query = """
SELECT
p.product_name,
SUM(oi.quantity) AS total_quantity
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
JOIN orders o
ON oi.order_id = o.order_id
WHERE DATE(o.order_date)
BETWEEN %s AND %s
GROUP BY p.product_name
ORDER BY total_quantity DESC
LIMIT 3;
"""

cursor.execute(top_query, (start_date, end_date))

top_products = cursor.fetchall()

for i, product in enumerate(top_products, start=1):
    print(f"{i}. {product[0]} - {product[1]} Units")

1. Novel - 123 Units
2. Mixer - 122 Units
3. Watch - 119 Units

Previous Period Comparison

In [9]:
previous_query = """
SELECT
ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent / 100)),2)
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
WHERE DATE(o.order_date) < %s;
"""

cursor.execute(previous_query, (start_date,))

previous_revenue = cursor.fetchone()[0]

if previous_revenue is None or previous_revenue == 0:
    revenue_change = 0
else:
    revenue_change = ((summary[1] - previous_revenue) / previous_revenue) * 100


print("Current Revenue  : ₹", summary[1])
print("Previous Revenue : ₹", previous_revenue)
print("Revenue Change   :", round(revenue_change, 2), "%")

Current Revenue  : ₹ 2717167.91
Previous Revenue : ₹ None
Revenue Change   : 0 %

close connection

In [10]:
cursor.close()
connection.close()

Phase 5 : Edge Case Handling

In [12]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="WJ28@KRHPS",
    database="ecommerce_order_analytics"
)

cursor = connection.cursor()

Test 1 : Invalid Order ID

1. What happens when order_items has an order_id not in orders?

In [13]:
def test_invalid_order_id():

    query = """
    SELECT *
    FROM order_items
    WHERE order_id NOT IN (
        SELECT order_id
        FROM orders
    );
    """

    cursor.execute(query)

    result = cursor.fetchall()

    print("\nTest 1 : Invalid Order ID")
    print("Records Found :", len(result))

test_invalid_order_id()

Test 1 : Invalid Order ID
Records Found : 0

2. What happens when discount_percent > 100?

In [14]:
def test_discount():

    query = """
    SELECT *
    FROM order_items
    WHERE discount_percent > 100;
    """

    cursor.execute(query)

    result = cursor.fetchall()

    print("\nTest 2 : Discount Greater Than 100")
    print("Records Found :", len(result))

test_discount()

Test 2 : Discount Greater Than 100
Records Found : 0

3. What happens when quantity is 0?

In [15]:
def test_zero_quantity():

    query = """
    SELECT *
    FROM order_items
    WHERE quantity = 0;
    """

    cursor.execute(query)

    result = cursor.fetchall()

    print("\nTest 3 : Quantity Equal to Zero")
    print("Records Found :", len(result))

test_zero_quantity()

Test 3 : Quantity Equal to Zero
Records Found : 0

4. What happens when order_date is in the future?

In [16]:
def test_future_date():

    query = """
    SELECT *
    FROM orders
    WHERE order_date > CURDATE();
    """

    cursor.execute(query)

    result = cursor.fetchall()

    print("\nTest 4 : Future Order Date")
    print("Records Found :", len(result))

test_future_date()

Test 4 : Future Order Date
Records Found : 0

Final Summary

In [18]:
print("\n========================================")
print("EDGE CASE TEST SUMMARY")
print("========================================")

print("Test 1 Completed : Invalid Order ID")
print("Test 2 Completed : Discount Validation")
print("Test 3 Completed : Zero Quantity")
print("Test 4 Completed : Future Date Validation")

print("\nAll Edge Case Tests Executed Successfully!")

========================================
EDGE CASE TEST SUMMARY
========================================
Test 1 Completed : Invalid Order ID
Test 2 Completed : Discount Validation
Test 3 Completed : Zero Quantity
Test 4 Completed : Future Date Validation

All Edge Case Tests Executed Successfully!

In [19]:
cursor.close()
connection.close()