1.Load a CSV dataset into a Pandas DataFrame.

In [1]:
import pandas as pd
csv=pd.read_csv("/content/Combined_dataset.csv")
csv

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

 2.Explore data (head/tail, shape, columns, data types).

In [2]:
csv.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [3]:
csv.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [5]:
csv.shape

(1000, 24)

In [6]:
csv.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [10]:
csv.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

3.Handle missing values (identify, fill/drop).

In [11]:
csv.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False

In [13]:
csv.fillna(0)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",0,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",0,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",0,0,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",0,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",0,0,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,0,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",0,0,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""pi-13698258""]",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",0,0,"[{""size"":""Onesize""}]",0,0,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",0,Tru███m R███il,"[{""size"":""Onesize""}]",0,Sho███o. ███-10█████████enu███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",0,0,"[{""size"":""Medium""}]",0,0,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [14]:
csv.dropna()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
418,18689340,Flying Machine,Women Black Wide Leg High-Rise Light Fade Crop...,4.3,36,2349,42.0,"""₹1,362.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":1,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-18689340_cae700""]",10T███LOO███DU █████████ITY███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
752,18241626,Roadster,The Lifestyle Co. Women Maroon & Black Ribbed...,4.5,25,1699,62.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""36.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
753,18241400,Roadster,Women Black & White Geometric Pullover Sweater,3.8,57,2699,5.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":5,""2_stars"":4,""3_stars"":13,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""B...","[""rw-18241400_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
754,18241644,Roadster,The Lifestyle Co. Women Pink Acrylic Pullover,4.3,55,1999,62.0,"""₹759.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""38.0in"",""value_name"":""B...","[""rw-18241644_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
755,18240570,all about you,Women Navy Blue & Red Checked Pullover,4.3,53,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18240570_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
756,18240582,all about you,Women Maroon Cable Knit Pullover,4.4,39,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""80"",""value_name"":""Fit, A Littl...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
757,18337610,Roadster,Men Navy Blue Self-Striped Cardigan,4.3,32,2299,67.0,"""₹758.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""S"",""value"":""37.0in"",""value_name"":""Ch...","[""rw-18337610_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
760,18241294,Roadster,Women Lavender & Off White Striped Pullover,4.3,90,1699,5.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":8,""2_stars"":0,""3_stars"":7,""4_stars"":...","[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
762,18241298,Roadster,The Lifestyle Co. Women Lavender Self-Design ...,4.3,59,1999,70.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":8,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""rw-18241298_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
904,18937522,her by invictus,V-Neck Textured Regular Top,3.9,57,1298,65.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":4,""3_stars"":6,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, A Littl...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937522_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

4.Perform basic operations (filter rows, select columns).

In [15]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [16]:
csv[csv["rating"] >= 3.8]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Br ███erp███es,"[{""size"":""Onesize""}]",NaN,Kha███ no███122█████████lhi██████████████████,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [19]:
rows =  {
    "title" : ["Tommy Hilfiger" , "Lavie" , "Fastrack"],
     "rating" : [4.5 , 4.4 , 5.0],
     "discount" : [35.0 , 65.0 , 20.0]
}
csv=csv.filter(rows)

In [20]:
csv.usecol=["title", "rating", "discount"]

/tmp/ipykernel_2523/3617570091.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  csv.usecol=["title", "rating", "discount"]

In [21]:
csv.rating

0      3.8
1      4.5
2      4.4
3      4.4
4      4.7
      ...
995    3.5
996    5.0
997    2.8
998    4.3
999    3.8
Name: rating, Length: 1000, dtype: float64

In [22]:
csv.columns

Index(['title', 'rating', 'discount'], dtype='object')

In [26]:
csv

              title  rating  discount
0       Lino Perros     3.8      58.0
1    Tommy Hilfiger     4.5      35.0
2             Lavie     4.4      65.0
3            F Gear     4.4      52.0
4         MYTRIDENT     4.7      17.0
..              ...     ...       ...
995           KREDO     3.5      50.0
996           GUESS     5.0      45.0
997        GIORDANO     2.8      50.0
998        Fastrack     4.3      20.0
999         BOLDFIT     3.8      31.0

[1000 rows x 3 columns]

5.Remove duplicates.

In [25]:
csv.drop_duplicates()

              title  rating  discount
0       Lino Perros     3.8      58.0
1    Tommy Hilfiger     4.5      35.0
2             Lavie     4.4      65.0
3            F Gear     4.4      52.0
4         MYTRIDENT     4.7      17.0
..              ...     ...       ...
995           KREDO     3.5      50.0
996           GUESS     5.0      45.0
997        GIORDANO     2.8      50.0
998        Fastrack     4.3      20.0
999         BOLDFIT     3.8      31.0

[946 rows x 3 columns]

 6.Create a derived column (total_amount = price * quantity).

In [35]:
import pandas as pd
csv=pd.read_csv("/content/Combined_dataset.csv")
csv

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [36]:
csv["total_amount"]=csv["final_price"]* csv["ratings_count"]

In [39]:
csv.drop([
    "currency",
    "images",
    "amount_of_stars",
    "what_customers_said",
    "seller_name",
    "sizes",
    "videos",
    "seller_information",
    "variations",
    "best_offer",
    "more_offers"
],axis=1,inplace=True)

In [40]:
csv

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,delivery_options,product_details,breadcrumbs,product_specifications,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue solid backpackNon-Pa...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",backpacks,"""₹3,995.00""""₹3,995.00""""₹3,995.00""""₹3,995.00""""₹..."
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue backpackNon-Padded h...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",backpacks,"""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹..."
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",backpacks,"""₹2,999.00""""₹2,999.00""""₹2,999.00""""₹2,999.00""""₹..."
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...",backpacks,"""₹1,675.00""""₹1,675.00""""₹1,675.00""""₹1,675.00""""₹..."
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue solid bath robe, has a sh...","[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...",bath-robe,"""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Features:Nothing about the For...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",watches,"""₹11,890.00""""₹11,890.00""""₹11,890.00""""₹11,890.0..."
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",watches,"""₹8,900.00""""₹8,900.00""""₹8,900.00""""₹8,900.00""""₹..."
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Case style: Analogue watch, ha...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Dial Material"",""specif...",watches,"""₹7,950.00""""₹7,950.00""""₹7,950.00""""₹7,950.00""""₹..."
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",watches,"""₹2,636.00""""₹2,636.00""""₹2,636.00""""₹2,636.00""""₹..."
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""","[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: One yoga matColou...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Mat Thickness"",""specif...",yoga-mats,"""₹699.00""""₹699.00""""₹699.00""""₹699.00""""₹699.00""""..."

In [44]:
csv.rename(columns={"ratings_count" : "quantity"},inplace=True)

In [45]:
csv.columns

Index(['product_id', 'title', 'product_description', 'rating', 'quantity',
       'initial_price', 'discount', 'final_price', 'delivery_options',
       'product_details', 'breadcrumbs', 'product_specifications', 'category',
       'total_amount'],
      dtype='object')

In [46]:
csv["final_price"] = (
    csv["final_price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace('"', "", regex=False)
    .astype(float)
)

In [47]:
csv["final_price"]=csv["final_price"].astype(int)

In [48]:
csv["quantity"]=csv["quantity"].astype(int)

In [49]:
csv

,product_id,title,product_description,rating,quantity,initial_price,discount,final_price,delivery_options,product_details,breadcrumbs,product_specifications,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue solid backpackNon-Pa...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",backpacks,"""₹3,995.00""""₹3,995.00""""₹3,995.00""""₹3,995.00""""₹..."
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue backpackNon-Padded h...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",backpacks,"""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹..."
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",backpacks,"""₹2,999.00""""₹2,999.00""""₹2,999.00""""₹2,999.00""""₹..."
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...",backpacks,"""₹1,675.00""""₹1,675.00""""₹1,675.00""""₹1,675.00""""₹..."
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue solid bath robe, has a sh...","[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...",bath-robe,"""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Features:Nothing about the For...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",watches,"""₹11,890.00""""₹11,890.00""""₹11,890.00""""₹11,890.0..."
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",watches,"""₹8,900.00""""₹8,900.00""""₹8,900.00""""₹8,900.00""""₹..."
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Case style: Analogue watch, ha...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Dial Material"",""specif...",watches,"""₹7,950.00""""₹7,950.00""""₹7,950.00""""₹7,950.00""""₹..."
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",watches,"""₹2,636.00""""₹2,636.00""""₹2,636.00""""₹2,636.00""""₹..."
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: One yoga matColou...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Mat Thickness"",""specif...",yoga-mats,"""₹699.00""""₹699.00""""₹699.00""""₹699.00""""₹699.00""""..."

In [50]:
csv["total_amount"]=csv["final_price"]* csv["quantity"]

In [52]:
csv.total_amount

0        59925
1       194233
2       677774
3      1762100
4        34788
        ...
995     130790
996     195800
997      39750
998      44812
999     112539
Name: total_amount, Length: 1000, dtype: int64

In [53]:
csv

,product_id,title,product_description,rating,quantity,initial_price,discount,final_price,delivery_options,product_details,breadcrumbs,product_specifications,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue solid backpackNon-Pa...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",backpacks,59925
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue backpackNon-Padded h...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",backpacks,194233
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",backpacks,677774
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...",backpacks,1762100
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue solid bath robe, has a sh...","[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...",bath-robe,34788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Features:Nothing about the For...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",watches,130790
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",watches,195800
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Case style: Analogue watch, ha...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Dial Material"",""specif...",watches,39750
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...",watches,44812
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: One yoga matColou...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Mat Thickness"",""specif...",yoga-mats,112539

In [58]:
csv.drop ([
    "delivery_options",
    "product_details",
    "breadcrumbs",
    "product_specifications"
],axis=1,inplace=True)

In [59]:
csv

,product_id,title,product_description,rating,quantity,initial_price,discount,final_price,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995,backpacks,59925
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899,backpacks,194233
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999,backpacks,677774
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675,backpacks,1762100
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899,bath-robe,34788
...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890,watches,130790
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900,watches,195800
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950,watches,39750
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636,watches,44812
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699,yoga-mats,112539

In [60]:
csv.to_csv("Cleaned_Data.csv",index=False)

In [61]:
from google.colab import files
files.download("Cleaned_Data.csv")